### ISSUE TITLE
Protocol-buffers-encode中Varints编码举例有误

### ISSUE THREAD

**Issue by BillXiangXBB** [halfrost/Halfrost-Field#11]
原文：
Varint 的编码，以 300 举例：

1. 100101100 | 10000000 = 1 1010 1100
2. 110101100 >> 7 = 1010 1100
3. 100101100 >> 7 = 10 = 0000 0010
4. 1010 1100 0000 0010 (最终 Varint 结果)

此处，第二步有误，第一步得出的结果取后8位就是前面一个字节的编码结果，根据源码应该没有这一步。

**Comment by halfrost** [comment]
嗯，你说的对，我更改啦。感谢指出错误 🙏
