### ISSUE TITLE
s2架服务

### ISSUE THREAD

**Issue by wyfSunflower** [halfrost/Halfrost-Field#16]
你好！请问你用S2-geometry写的应用是用哪个版本的，最终需要架服务么？我用C++写的，现在不知道怎样用nodejs架服务，能指点一下么？多谢

**Comment by halfrost** [comment]
我用的是 golang 的版本。C++ 的这个 repo 我也看过，这个只能算是一个算法的实现，具体想要成为一个服务，是需要在服务器上部署的。nodejs 写一个服务，跑在服务器上，开放一个端口给外部调用，写一个路由对应一个 handler，这个 handler 进来就是你这块 S2 的处理逻辑。
