### ISSUE TITLE
请问这是那个版本的swift  我这边v4.2.1 这个语法似乎无法实现 编译的都过不去

### ISSUE THREAD

**Issue by RunsCode** [halfrost/Halfrost-Field#17]
![wx20190219-151427](https://user-images.githubusercontent.com/25574478/52996643-2e98a480-3459-11e9-9779-4c3367fa2bc6.png)

**Comment by halfrost** [comment]
我这里的 Swift 的版本是 2.X 的。现在应该发生了很多变化了。
