### ISSUE TITLE
深入解析 Go 中 Slice 底层实现 中代码bug

### ISSUE THREAD

**Issue by shihuimiao** [halfrost/Halfrost-Field#18]
https://github.com/halfrost/Halfrost-Field/blob/master/contents/Go/go_slice.md

```$go
func main() {
	arrayA := [2]int{100, 200}
	testArrayPoint(&arrayA)   // 1.传数组指针
	arrayB := arrayA[:]
	testArrayPoint(&arrayB)   // 2.传切片
	fmt.Printf("arrayA : %p , %v\n", &arrayA, arrayA)
}

func testArrayPoint(x *[]int) {
	fmt.Printf("func Array : %p , %v\n", x, *x)
	(*x)[1] += 100
}
```
testArrayPoint方法传入的是切片的指针
testArrayPoint(&arrayA)   // 1.传数组指针   这里不能传入数据指针
@halfrost

**Comment by halfrost** [comment]
哎呀。。之前你提的问题我没有注意邮件。今天有其他的 issue 我才发现。你说的意思是 testArrayPoint(&arrayA) // 这里传入的是切片的指针，是么？
