### ISSUE TITLE
神奇的德布鲁因序列的补充

### ISSUE THREAD

**Issue by wellcheng** [halfrost/Halfrost-Field#2]
神奇的德布鲁因序列中：

第一次没看明白那个魔术的描述，我觉得应该加一个限定：魔术师实现是知道牌的排列顺序的，切牌后仍然是一个环路，只是魔术师不知道起点现在是哪张牌了。

**Comment by halfrost** [comment]
嗯嗯。。你是简书上的那个人么？哈哈。。简书上也有一个人问了一个和你一样的问题。我一会改一下描述。其实应该说切牌只能上下切，不能乱切。因为如果上下切牌，由于循环序列，上下切牌都是一样的，并不影响全排列。我这样说，应该更清楚吧。

**Comment by halfrost** [comment]
关于牌的顺序其实是不必知道的。不必知道整个32张牌的顺序，（当然知道会更好），因为每5个都是可以推算的。只要能保证牌是一个德布鲁因序列就可以，这样就能保证是一个全排列。

**Comment by halfrost** [comment]
@wellcheng 我更新了一下文章，你看看 f3b7780 这个commit 哈~

**Comment by wellcheng** [comment]
还有一个疑问，为什么只需要知道谁拿了黑色的牌，就能确定其在序列中的位置？
我的理解是，如果知道某个人拿了黑色牌，我只能确定他所代表的 5 bit 序列为 「0xxxx」，按理说，我只有知道他具体是黑色的哪张牌，我才能知道他的全排列，比如 01001 ，然后根据顺序借此推算出前后。

**Comment by halfrost** [comment]
嗯嗯。我懂你说的意思。还是需要知道初始的32张牌的顺序的。开始让观众洗牌，默认的就给他们心里暗示，这些牌是都洗过的，顺序变过了。

**Comment by halfrost** [comment]
感谢你的补充，我更新到文章里面去了。具体见 6f6c3e8 这个commit，感谢感谢~
