### ISSUE TITLE
HTTPS-begin中Alter和Change Cipher Spec Protocol消息在TLS1.2应该被加密了吧

### ISSUE THREAD

**Issue by YifangY** [halfrost/Halfrost-Field#20]
我看到RFC5246中7.2节说到Alert是被加密的
https://tools.ietf.org/html/rfc5246#section-7.2
Like other messages, alert messages are encrypted and compressed, as specified by the current connection state.
Change Cipher Spec Protocol也是被加密的
The protocol consists of a single message, which is encrypted and compressed under the current (not the pending) connection state.

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by LuoZijun** [comment]
@YifangY 

> as specified by the current connection state.

当收到 `ChangeCipherSpec record` 后，后面的 Record 都是加密了的（当然也包括 AlertRecord）。

`ChangeCipherSpec` 本身是没有加密的。因为他没有 content.
