### ISSUE TITLE
请教一个关于cell id的问题

### ISSUE THREAD

**Issue by wushuangxiaoyu** [halfrost/Halfrost-Field#23]
你好
在看cell_id 源码的时候看到这样一个代码,不求甚解，盼大佬解答:
![image](https://user-images.githubusercontent.com/26874082/79547335-566bb280-80c6-11ea-98bd-fbc08623bb7e.png)
zhe'g
这个next 就是把最小的精度位置直接+1了
希尔伯特的最小单元不是有4种u型么。。按理说 +1 不一定是cellId的next啊
那为啥这里是这样处理的呢？

**Comment by halfrost** [comment]
这里 + 1 是在 U 型上变换到了下一个单元，计算 cellid 是在 S2CellId 那个函数里面计算的。
