### ISSUE TITLE
想问一下您是用的什么软件画的图喔，

### ISSUE THREAD

**Issue by Yangzhoufly** [halfrost/Halfrost-Field#24]
嘻嘻，学习一下

**Comment by halfrost** [comment]
用 sketch 画的

**Comment by Yangzhoufly** [comment]
![image](https://user-images.githubusercontent.com/34160305/86432026-f8e01d00-bd28-11ea-88e3-749eff0c197c.png)

这个图也是用sketch 画的吗

**Comment by halfrost** [comment]
是的，都是用 sketch 的。。之前有用过 ps，但是自由度没有 sketch 高，所以后面都用 sketch 了。
