### ISSUE TITLE
细节错误

### ISSUE THREAD

**Issue by MelodyD** [halfrost/Halfrost-Field#25]
在“Google S2 中 cellid 是如何生成的“一文中：
>“上面这一步是把经纬度转换成弧度。由于经纬度是角度，弧度转角度乘以 π / 180° 即可”。

应该是“角度转弧度乘以 π / 180° 即可。“吧。
此外还有问题想请教一下，LatLngFromDegree()输入的经纬度参数的格式是 ”d.ddddd"还是度分秒的格式啊。

**Comment by halfrost** [comment]
谢谢你指出错误，这里你说的是对的，我已经更正了。

LatLngFromDegree()输入的经纬度这里是度分秒的格式。
