### ISSUE TITLE
how is used  afalg function on openssl？

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [halfrost/Halfrost-Field#26]
1.看到您写的tls协议分析很透彻，确认是个英文水平和代码逻辑很好的大牛，不知道可否提需求如标题？
2.afalg 和 ktls 为什么会同时出现？

**Comment by halfrost** [comment]
你这个问题我还真没研究过。我研究 OpenSSL 主要还是协议层的一些东西，和性能优化。里面这些内部实现我还没有深入研究过 😂 
Ps: 楼主是要改里面的东西么？还是基于 OpenSSL 实现一些新功能？

**Comment by yangyangtiantianlonglong** [comment]
现在的tls只是在用户态给传输层的buf进行加解密实现，afalg和ktls会在内核态对协议栈数据进行加解密
1.openssl的demo实现并没有真正内核态的用例，我想要知道afalg怎样使用
2.既然已经有afalg，为什么在openssl-3.0.0里面还加入了ktls

**Comment by halfrost** [comment]
好吧，你研究的这些我也没有弄过。帮不到你的忙了。👍🏻 我觉得你才是大牛~
