### ISSUE TITLE
请问您博客的框架是怎么写的？

### ISSUE THREAD

**Issue by OctopusLian** [halfrost/Halfrost-Field#27]
你好，关注您好久了。今天看到您的博客框架，标题清晰，层级合理，我想问下您是自学前端写的博客页面吗？  
我之前用过`hexo`和`ghost`，目前在用`hexo`，不过必须将仓库名 命名为 username.github.io 的形式。
感谢回复~

**Comment by halfrost** [comment]
我的博客主题在另外一个仓库里面~哈哈~我刚刚毕业那会算是半个前端。。在工作中实践，参与业务迭代，实践中学习就学的很快。当然有问题不懂就问，同事帮了我很多，进步也很快，我很感激公司给的机会和同事们的帮助~

**Comment by OctopusLian** [comment]
哈哈，原来如此。我毕业就做的后端，对前端一窍不通，之前看您的博客页面第一想到的是`ghost`风格搭的。不过最近部门也在让我自学下前端，看起来蛮有趣的~

**Comment by halfrost** [comment]
哦，关于这个问题，我推荐你一个 chrome 的插件，wappalyzer，这个插件会把 DOM 里面用到的框架都分析出来。有些可能还是 header 里面带的，比如 nginx 一些版本号，它都会帮你分析出来。这样你看一个网页用了哪些框架，就很清楚。我 chrome 安了这个。所以每个网站大体用了什么框架基本都清楚。。另外也有一些屏蔽的方法，能让这个插件扫描不到的方法。如果网站作者故意那么做，就扫不到了。。例如不想让对方知道 nginx 版本，或者 jQuery 的版本，会特意隐藏。这些版本有些有漏洞，怕对方攻击。当然一般都不会去隐藏的。。很多人都没想着去隐藏这些信息。所以用这个插件基本上都能看到。

**Comment by OctopusLian** [comment]
好的，非常感谢！
