### ISSUE TITLE
Ghost博客主题

### ISSUE THREAD

**Issue by xuyisheng** [halfrost/Halfrost-Field#30]
想咨询下你的ghost博客的主题是哪个？

**Comment by halfrost** [comment]
> 想咨询下你的ghost博客的主题是哪个？

@xuyisheng 你好，是这个：https://github.com/halfrost/Prometheus。（可惜没多少人点 star，可能写的不好😭）

**Comment by xuyisheng** [comment]
最近也在折腾ghost，不知道能不能加个微信 13641719651 thanks

**Comment by halfrost** [comment]
加你了哈，那我就 close 这个 issue 啦~
