### ISSUE TITLE
細節錯誤

### ISSUE THREAD

**Issue by bominn** [halfrost/Halfrost-Field#32]
hi 感謝對 flatbuffer encode 的詳細解說，
雖然沒寫過 go 但還是大致了解了 encode 的原理了

FlatBuffers 之 Encode  內序列化 table 的部分

` 最后一步需要修正 sword 对象头部的 offset，修改成距离 vtable 的 offset。由于当前 vtable 在低地址，所以 sword 对象在它的右边，offset 为正数，offset = vtable size = 8 字节。对应代码实现见第 10 步。 `

看起來第9步才是對的

**Comment by halfrost** [comment]
@bominn 谢谢你指出错误，已经更正啦。
