### ISSUE TITLE
感觉是用机器翻译的

### ISSUE THREAD

**Issue by zhengshuxin** [halfrost/Halfrost-Field#33]
感觉大部分都是用机器翻译的，太难懂了：（

**Comment by chikwongzhao** [comment]
我感觉也是，很多地方读着都特别别扭。。。

**Comment by halfrost** [comment]
😢  看来我翻译的很差啊。（有些实在不好翻译

**Comment by jievince** [comment]
> 😢 看来我翻译的很差啊。（有些实在不好翻译

作者你好,感觉从i,j到pos转换那里讲的很清楚, 前面的部分讲的很好

**Comment by zhengshuxin** [comment]
多谢作者的无私奉献，我最近正准备参考一些文档实现HTTP2功能，从网上搜到了这个项目。

**Comment by halfrost** [comment]
> 多谢作者的无私奉献，我最近正准备参考一些文档实现HTTP2功能，从网上搜到了这个项目。

@zhengshuxin 您好呀。欢迎随时交流🤪 我之前在公司里面是做网络层这一块的，从第三层到第七层都有一些研究心得。
