### ISSUE TITLE
谁知道content-length 怎么解析的?

### ISSUE THREAD

**Issue by xengine-qyt** [halfrost/Halfrost-Field#38]
前面都对,到CONTENT-LENGTH 解析的时候就不对了
为什么开头是00001111啊?什么意思.看不懂

![QQ图片20220413094501](https://user-images.githubusercontent.com/37919215/163082702-bd1c9156-a020-4ccc-8ba0-998db0e2e784.png)

**Comment by marlonxlj** [comment]
您好！
     收到您的来信！

**Comment by claviering** [comment]
It's the number of bytes of data in the body of the request or response

[http header](https://stackoverflow.com/questions/2773396/whats-the-content-length-field-in-http-header)

**Comment by marlonxlj** [comment]
您好！
     收到您的来信！
