### ISSUE TITLE
有没有考虑过做成一个 fastpages

### ISSUE THREAD

**Issue by chongchonghe** [halfrost/Halfrost-Field#40]
请问作者有没有考虑过把这里所有的 notebook 和 markdown 都放在一个 [fastpages](https://fastpages.fast.ai/) 里，这样阅读起来会方便太多，也方便对每一个 notebook 及时评论。

**Comment by marlonxlj** [comment]
您好！
     收到您的来信！

**Comment by halfrost** [comment]
> 请问作者有没有考虑过把这里所有的 notebook 和 markdown 都放在一个 [fastpages](https://fastpages.fast.ai/) 里，这样阅读起来会方便太多，也方便对每一个 notebook 及时评论。

@chongchonghe 其实做了。文章都在我的博客里面了。网页版在这里：https://halfrost.com/

**Comment by chongchonghe** [comment]
> 

哦好，谢谢
