### ISSUE TITLE
Remove colon(:) from filename

### ISSUE THREAD

**Issue by bohrasankalp** [halfrost/Halfrost-Field#43]
Can you please remove colon(:) & chinese unicode character from few filenames? Its difficult to clone on windows system.

**Comment by marlonxlj** [comment]
您好！
     收到您的来信！

**Comment by halfrost** [comment]
@bohrasankalp For example? You can make a pull request to fix it.

**Comment by bohrasankalp** [comment]
@halfrost I can't even clone it, becoz windows doesn't allow colon(:) in filename. Example `contents->Go->LRU:LFU_interview.md` is invalid filename for me. 

Replace it with `-` or `_`. You could run this command in terminal to find all files, `find . -type f -name "*:*.*"`.

**Comment by halfrost** [comment]
@bohrasankalp I have fixed it. Please pull it again.

**Comment by bohrasankalp** [comment]
@halfrost Thanks.
