### ISSUE TITLE
github徽章

### ISSUE THREAD

**Issue by diankuanghuolong** [halfrost/Halfrost-Field#7]
你好，你的徽章好棒啊。我想问下，记录下载次数的徽章咋弄呢？我的下载次数统计是无效的，没找到好的方法。

**Comment by halfrost** [comment]
你好，下载次数的徽章是在哪里的？？我这个 repo 里面没有加这个徽章吧。

**Comment by halfrost** [comment]
哦哦。。给你一个网站，基本上徽章的例子都在这里有，http://shields.io/，哈哈哈。。够用了吧。

**Comment by diankuanghuolong** [comment]
好的，万分感谢。🙏哈哈哈
