### ISSUE TITLE
Protocol-buffers-encode文章中的一个小BUG

### ISSUE THREAD

**Issue by duzhe** [halfrost/Halfrost-Field#8]
Halfrost-Field/contents/Protocol/Protocol-buffers-encode.md

"由于 300 超过了 7 位（Varint 一个字节只有 7 位能用来表示数字，最高位 msb 用来表示后面是否有更多字节），所以 300 需要用 2 个字节来表示。"
"读到这里可能有读者会问了，Varint 不是为了紧凑 int 的么？那 300 本来可以用一个字节表示，现在变成 2 个字节了，哪里紧凑了，花费的空间反而变多了？！"

1个字节最多表示0-255， 300即便不用varint表示也是不能用1个字节来表示的。改成用200做例子就恰当了。

**Comment by halfrost** [comment]
嗯。。了解你的意思。。不过这里其实是想比较 Int32 下存储 300 和 varint 存储 300 的空间比较。。我去改一下。不然这样描述容易让你们误解。
